basePath: /
definitions:
  models.Node:
    properties:
      comment:
        type: string
      country:
        type: string
      id:
        type: integer
      ip:
        type: string
      is_online:
        type: boolean
      password:
        type: string
      port:
        type: integer
      ssh_port:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API для управления пользователями и Xray
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Xray Management API
  version: "1.0"
paths:
  /api/nodes:
    get:
      description: Получает список всех VPN-узлов
      produces:
      - application/json
      responses:
        "200":
          description: Список узлов, пароли не возвращаются
          schema:
            items:
              $ref: '#/definitions/models.Node'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список всех узлов
      tags:
      - узлы
    post:
      consumes:
      - application/json
      description: Создает новый VPN-узел с указанными данными
      parameters:
      - description: Данные узла
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/models.Node'
      produces:
      - application/json
      responses:
        "201":
          description: Узел создан, пароль не возвращается
          schema:
            $ref: '#/definitions/models.Node'
        "400":
          description: Неверный формат запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать новый узел
      tags:
      - узлы
  /api/nodes/{id}:
    delete:
      description: Удаляет VPN-узел по его ID
      parameters:
      - description: ID узла
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Нет содержимого
        "400":
          description: Неверный ID узла
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Узел не найден
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить узел
      tags:
      - узлы
    get:
      description: Получает VPN-узел по его идентификатору
      parameters:
      - description: ID узла
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Детали узла, пароль не возвращается
          schema:
            $ref: '#/definitions/models.Node'
        "400":
          description: Неверный ID узла
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Узел не найден
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить узел по ID
      tags:
      - узлы
    put:
      consumes:
      - application/json
      description: Обновляет существующий VPN-узел по его ID
      parameters:
      - description: ID узла
        in: path
        name: id
        required: true
        type: integer
      - description: Обновленные данные узла
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/models.Node'
      produces:
      - application/json
      responses:
        "200":
          description: Обновленный узел, пароль не возвращается
          schema:
            $ref: '#/definitions/models.Node'
        "400":
          description: Неверный формат запроса или ID узла
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Узел не найден
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить узел
      tags:
      - узлы
swagger: "2.0"
